# Generated by Django 2.2.12 on 2021-04-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20210429_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='favorites',
        ),
        migrations.AlterField(
            model_name='ad',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='ads'),
        ),
    ]
