# Generated by Django 2.2.12 on 2021-04-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_auto_20210430_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='picture',
            field=models.ImageField(blank=True, default='home/static/img/image.jpg', null=True, upload_to='ads'),
        ),
    ]
