# Generated by Django 2.2.12 on 2021-05-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_auto_20210430_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='picture',
            field=models.ImageField(blank=True, default='/default/image.jpg', null=True, upload_to='anuncios'),
        ),
    ]
