# Generated by Django 2.2.12 on 2021-05-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_auto_20210503_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='picture',
            field=models.ImageField(blank=True, default='anuncios/image.jpg', null=True, upload_to='anuncios'),
        ),
    ]
