# Generated by Django 2.2.12 on 2021-05-11 08:16

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_auto_20210503_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='picture',
            field=stdimage.models.StdImageField(blank=True, default='anuncios/image.jpg', upload_to='anuncios'),
        ),
    ]
