# Generated by Django 2.2.12 on 2021-05-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_auto_20210511_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='picture',
            field=models.ImageField(blank=True, default='anuncios/image.jpg', null=True, upload_to='anuncios'),
        ),
    ]
